# Generated by Django 5.2.7 on 2025-12-09 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('compteur_alerte', models.IntegerField(default=0)),
                ('temperature_max', models.FloatField(default=0)),
                ('resolu', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('accuse_reception', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dht11',
            old_name='timestamp',
            new_name='dt',
        ),
        migrations.RenameField(
            model_name='dht11',
            old_name='humidity',
            new_name='hum',
        ),
        migrations.RenameField(
            model_name='dht11',
            old_name='temperature',
            new_name='temp',
        ),
    ]
