# Generated by Django 5.2.7 on 2026-01-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accusereception',
            name='vu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='accusereception',
            unique_together={('incident', 'operateur')},
        ),
    ]
